name: 'Redeploy'
description: 'Redeploy a project using the Obelis API'
author: 'Obelis AI'

inputs:
  project_id:
    description: 'The ID of the project to redeploy'
    required: true
  api_key:
    description: 'The API key to use for authentication'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Redeploy
      id: redeploy
      shell: bash
      run: |
        echo "ðŸŒ Calling Obelis API redeploy endpoint..."
        
        # Construct the full API URL
        API_URL="https://api.obelis.ai/deploy/action/${{ inputs.project_id }}"
        
        # Prepare curl command with authentication
        CURL_CMD="curl -s -w '%{http_code}' --max-time 300"
        
        # Add method (POST)
        CURL_CMD="$CURL_CMD -X POST"
        
        # Add API key header
        CURL_CMD="$CURL_CMD -H 'X-API-Key: ${{ inputs.api_key }}'"
        
        # Add content type header
        CURL_CMD="$CURL_CMD -H 'Content-Type: application/json'"
        
        # Add URL
        CURL_CMD="$CURL_CMD '$API_URL'"
        
        
        # Execute curl and capture response
        RESPONSE=$(eval $CURL_CMD)
        STATUS_CODE="${RESPONSE: -3}"
        RESPONSE_BODY="${RESPONSE%???}"
        
        echo "status=$STATUS_CODE" >> $GITHUB_OUTPUT
        
        # Output response in collapsible section
        echo "::group::Response details"
        echo "Status: $STATUS_CODE"
        echo "Body: $RESPONSE_BODY"
        echo "::endgroup::"
        
        echo "response<<EOF" >> $GITHUB_OUTPUT
        echo "$RESPONSE_BODY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Check if request was successful
        PROJECT_URL="https://app.obelis.ai/projects/${{ inputs.project_id }}"
        if [ "$STATUS_CODE" -ge 200 ] && [ "$STATUS_CODE" -lt 300 ]; then
          echo "::notice::Redeploy started successfully (Status: $STATUS_CODE)"
          echo "::notice::Project: $PROJECT_URL"
          echo "success=true" >> $GITHUB_OUTPUT
          echo "project_url=$PROJECT_URL" >> $GITHUB_OUTPUT
        else
          echo "::error::Redeploy failed to start (Status: $STATUS_CODE)"
          echo "::error::Response: $RESPONSE_BODY"
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi

branding:
  icon: 'cloud'
  color: 'black'